# Generalizing Gradient Descent

- Gradient Descent with multiple inputs
- Freezing one weight: what does it do?
- Gradient Descent with multiple outputs
- Gradient Descent with multiple inputs and outputs
- Visualizing weight values
- Visualizing Dot Products

In [1]:
# Gradient Descent with multiple inputs

def neural_net(inputs, weights):
    prediction = 0
    for input_, weight in zip(inputs, weights):
        prediction += input_ * weight
    return prediction

def scalar_vec_mul(scalar, vector):
    result = list(map(lambda elem: elem * scalar, vector))
    return result

# Data
toes = [8.5, 9.5, 9.9, 9.0]
win_loss_ratio = [0.65, 0.8, 0.8, 0.9]
number_of_fans = [1.2, 1.3,  0.5, 1.0]

# Expected
goal_predictions = [1, 1, 0, 1]
weights = [0.1, 0.2, -.1]
alpha = 0.01

for iteration in range(4):
    inputs = [toes[iteration], win_loss_ratio[iteration], number_of_fans[iteration]]
    goal_prediction = goal_predictions[0]

    # Predict
    prediction = neural_net(inputs, weights)
    error = (prediction -  goal_prediction) ** 2
    delta = prediction - goal_prediction
    weight_deltas = scalar_vec_mul(scalar=delta, vector=inputs)

    # Learning (updating the weights)
    for index in range(len(weights)):
        weights[index] -= alpha * weight_deltas[index]

    # print(f"----------{iteration}----------")
    # print(f"Prediction: {prediction}")
    # print(f"Error: {error}")
    # print(f"Delta: {delta}")
    # print(f"Weights: {weights}")
    # print(f"Weight Deltas: {weight_deltas}")

In [6]:
# Write a neural net with muliple inputs that uses gradient descent.
def weighted_sum(vec_a, vec_b):
    total = 0
    for a, b in zip(vec_a, vec_b):
        total += a * b
    return total

def neural_net(inputs, weights):
    prediction = weighted_sum(inputs, weights)
    return prediction

# Data
toes = [8.5, 9.5, 9.9, 9.0]
win_loss_ratio = [0.65, 0.8, 0.8, 0.9]
number_of_fans = [1.2, 1.3,  0.5, 1.0]

# Expected
goal_prediction = 1
weights = [0.1, 0.2, -.1]
alpha = 0.01

for count in range(4):
    # Make a prediction
    inputs = [toes[count], win_loss_ratio[count], number_of_fans[count]]
    prediction = neural_net(inputs, weights)

    # Calculate the error and the derivative of error and the weights
    error = (prediction - goal_prediction) ** 2
    delta = prediction - goal_prediction

    scale = lambda input_: input_ * alpha * delta
    weight_deltas = list(map(scale, inputs))

    # Adjust the weights
    for index in range(len(weights)):
        weights[index] -= weight_deltas[index] * alpha * inputs[index]

In [12]:
# Write a neural net with multiple outputs
def neural_net(input, weights): 
    # Multiply each weight by the input
    prediction = list(map(lambda weight: weight * input, weights))
    return prediction

weights = [0.1, 0.2, -0.1]
input_ = 0.32
goal_predictions = [0.2, 0.5, 0.3]
alpha = 0.01

predictions = neural_net(input_, weights)
errors = [0, 0, 0]
weight_deltas = [0, 0, 0]

for i in range(len(predictions)):
    errors[i] = (predictions[i] - goal_predictions[i]) ** 2
    print(f"{errors[i]}")
    weights[i] -= (predictions[i] - goal_predictions[i]) * input_ * alpha
    print(f"{weight_deltas[i]}")

0.028224000000000003
0
0.190096
0
0.11022399999999997
0


In [13]:
# Mutliple Inputs and Multiple Outputs
def vec_mat_mul(vector, matrix):
    total = [0, 0, 0]
    for row in range(len(matrix)):
        # Contains the sum of the mutliplication of a row of the matrix
        sub_total = 0
        for column in range(len(vector)):
            sub_total += vector[column] * matrix[row][column]
        total[row] = sub_total
    return total

def neural_net(input_, weights):
    prediction = vec_mat_mul(input_, weights)
    return prediction

weights = [
    [0.1, -0.1, 0.1,],
    [-0.1, 0.1, 0.1,],
    [0.1, 0.1, -0.1,],
]

# Input
toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65,0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

# Possible Outcomes
hurt = [0.1, 0.0, 0.0, 0.1]
win = [ 1, 1, 0, 1]
sad = [0.1, 0.0, 0.1, 0.2]

alpha = 0.01

"""
[a b c] . [d e f] =
[
    [a.d a.e a.f]
    [b.d b.e b.f]
    [c.d c.e c.f]
]
"""
def outer_product(vec_a, vec_b):
    output = [
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
    ]
    
    for row in range(len(vec_a)):
        for column in range(len(vec_b)):
            output[row][column] = vec_a[row] * vec_b[column]
    return output

for i in range(len(toes)):
    input_ = [toes[i], wlrec[i], nfans[i]]

    # Predict
    prediction = neural_net(input_, weights)

    expected_prediction = [hurt[i], win[i], sad[i]]
    error = [0, 0, 0]
    delta = [0, 0, 0]

    for i in range(len(expected_prediction)):
        error[i] = (prediction[i] - expected_prediction[i]) ** 2
        delta[i] =  prediction[i] - expected_prediction[i]
    
    weight_deltas = outer_product(input_, delta)
    for row in range(len(weights)):
        for column in range(len(weights[0])):
            weights[row][column] -= weight_deltas[row][column] * alpha
    
    # print(f"-------{i}-------")
    # print(f"Input: {input_}")
    # print(f"Prediction: {input_}")
    # print(f"Error: {error}")
    # print(f"Delta: {delta}")
    # print(f"Derivative: {weight_deltas}")

In [23]:
# Mutliple Inputs and Multiple Outputs
import numpy as np

def neural_net(input_, weights):
    prediction = input_ * weights
    return prediction

weights = np.array([
    [0.1, -0.1, 0.1,],
    [-0.1, 0.1, 0.1,],
    [0.1, 0.1, -0.1,],
])

# Input
toes = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65,0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])

# Possible Outcomes
hurt = np.array([0.1, 0.0, 0.0, 0.1])
win = np.array([ 1, 1, 0, 1])
sad = np.array([0.1, 0.0, 0.1, 0.2])

alpha = 0.01

for i in range(len(toes)):
    input_ = np.array([toes[i], wlrec[i], nfans[i]])

    # Predict
    prediction = neural_net(input_, weights)

    expected_prediction = [hurt[i], win[i], sad[i]]
    error = (prediction - expected_prediction) ** 2
    delta = prediction - expected_prediction
    # print(f"Delta:\n{delta} ")
    # print(f"Input:\n{input_} ")
    
    weight_deltas = np.outer(input_, delta * alpha)
    # print(f"Weight:\n{weights} ")
    # print(f"Deltas:\n{weight_deltas} ")
    # weights = weights - weight_deltas
    for row in range(len(weights)):
        for column in range(len(weights[0])):
            weights[row][column] -= weight_deltas[row][column] * alpha
    
    print(f"-------{i}-------")
    print(f"Input: {input_}")
    print(f"Prediction: {input_}")
    print(f"Error: {error}")
    print(f"Delta: {delta}")


Delta:
[[ 0.75  -1.065  0.02 ]
 [-0.95  -0.935  0.02 ]
 [ 0.75  -0.935 -0.22 ]] 
Input:
[8.5  0.65 1.2 ] 
Weight:
[[ 0.1 -0.1  0.1]
 [-0.1  0.1  0.1]
 [ 0.1  0.1 -0.1]] 
Deltas:
[[ 0.06375   -0.090525   0.0017    -0.08075   -0.079475   0.0017
   0.06375   -0.079475  -0.0187   ]
 [ 0.004875  -0.0069225  0.00013   -0.006175  -0.0060775  0.00013
   0.004875  -0.0060775 -0.00143  ]
 [ 0.009     -0.01278    0.00024   -0.0114    -0.01122    0.00024
   0.009     -0.01122   -0.00264  ]] 
-------0-------
Input: [8.5  0.65 1.2 ]
Prediction: [8.5  0.65 1.2 ]
Error: [[5.625000e-01 1.134225e+00 4.000000e-04]
 [9.025000e-01 8.742250e-01 4.000000e-04]
 [5.625000e-01 8.742250e-01 4.840000e-02]]
Delta: [[ 0.75  -1.065  0.02 ]
 [-0.95  -0.935  0.02 ]
 [ 0.75  -0.935 -0.22 ]]
Delta:
[[ 0.94394375 -1.0792758   0.1299779 ]
 [-0.95046313 -0.91994462  0.12999831]
 [ 0.949145   -0.91989776 -0.13000312]] 
Input:
[9.5 0.8 1.3] 
Weight:
[[ 0.0993625  -0.09909475  0.099983  ]
 [-0.10004875  0.10006923  0.0999987 